package river:request;

interface r {
    record pair {
        name: string,
        value: string,
    }
    record request {
        path: string,
        method: string,
        headers: list<pair>,
    }
}

interface logger {
    debug: func(message: string);
    info: func(message: string);
    error: func(message: string);
}

world filter-world {
    import logger;
    use r.{request};
    export filter: func(req: request) -> bool;
}

